/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

/**
 *
 * @author FRADILA
 */
public class LAt1 extends javax.swing.JFrame {

    /**
     * Creates new form LAt1
     */
    public LAt1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Absen = new javax.swing.JTextField();
        Kelas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rdb1 = new javax.swing.JRadioButton();
        rdb2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("         Biodata");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 10, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 50, 50, 30);
        getContentPane().add(Nama);
        Nama.setBounds(230, 50, 290, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 100, 50, 30);
        getContentPane().add(Absen);
        Absen.setBounds(230, 100, 290, 30);

        Kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XI RPL 1", "XI RPL 2", "XI RPL 3", "XI RPL 4", "XI RPL 5", "XI RPL 6", "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X RPL 5", "X RPL 6", "X RPL 7", "X TKJ 1", "X TKJ 2", "X TKJ 3", "X TKJ 4", "X TKJ 5", "X TKJ 6 ", " ", " ", " " }));
        getContentPane().add(Kelas);
        Kelas.setBounds(230, 150, 290, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kelas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 150, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jurusan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 190, 60, 40);

        rdb1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdb1.setText("RPL");
        rdb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb1);
        rdb1.setBounds(240, 200, 70, 23);

        rdb2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdb2.setText("TKJ");
        rdb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb2);
        rdb2.setBounds(310, 200, 70, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 240, 60, 30);
        getContentPane().add(Alamat);
        Alamat.setBounds(230, 240, 280, 30);

        jButton1.setText("SEND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 310, 59, 20);

        jButton2.setText("EXIT");
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 310, 55, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\FRADILA\\Pictures\\Background\\violet-vector-leaves-circles-backgrounds-for-powerpoint1.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-830, -20, 2790, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb1ActionPerformed

    private void rdb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String nama = Nama.getText();
        String absen = Absen.getText();
        String kelas = Kelas.getSelectedItem().toString();
        String jurusan = "";
        String alamat = Alamat.getText();

        if (rdb1.isSelected())
        jurusan = "RPL";
        else if (rdb2.isSelected())
        jurusan = "TKJ";
        else
        jurusan = "";

        if (Kelas.getSelectedItem()== "XI RPL 1"){
        }
        if (Kelas.getSelectedItem()== "XI RPL 2"){
        }
        if (Kelas.getSelectedItem()== "XI RPL 3"){
        }
        if (Kelas.getSelectedItem()== "XI RPL 4"){
        }
        if (Kelas.getSelectedItem()== "XI RPL 5"){
        }
        if (Kelas.getSelectedItem()== "XI RPL 6"){
        }
        if (Kelas.getSelectedItem()== "X RPL 1"){
        }
        if (Kelas.getSelectedItem()== "X RPL 2"){
        }
        if (Kelas.getSelectedItem()== "X RPL 3"){
        }
        if (Kelas.getSelectedItem()== "X RPL 4"){
        }
        if (Kelas.getSelectedItem()== "X RPL 5"){
        }
        if (Kelas.getSelectedItem()== "X RPL 6"){
        }
        if (Kelas.getSelectedItem()== "X RPL 7"){
        }
        if (Kelas.getSelectedItem()== "X TKJ 1"){
        }
        if (Kelas.getSelectedItem()== "X TKJ 2"){
        }
        if (Kelas.getSelectedItem()== "X TKJ 3"){
        }
        if (Kelas.getSelectedItem()== "X TKJ 4"){
        }
        if (Kelas.getSelectedItem()== "X TKJ 5"){
        }
        if (Kelas.getSelectedItem()== "X TKJ 6"){

            Latihan2 kirim = new Latihan2();
            kirim.setVisible(false);
            kirim.Hasil1.setText(nama);
            kirim.Hasil2.setText(absen);
            kirim.Hasil3.setText(kelas);
            kirim.Hasil4.setText(jurusan);
            kirim.Hasil5.setText(alamat);

            //    tod.Hasil1.setText(nama);
            //    tod.Hasil2.setText(absen);
            //    tod.Hasil3.setText(kelas);
            //    tod.Hasil4.setText(jurusan);
            //    tod.Hasil5.setText(alamat);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAt1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAt1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Alamat;
    private javax.swing.JComboBox<String> Kelas;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rdb1;
    private javax.swing.JRadioButton rdb2;
    // End of variables declaration//GEN-END:variables
}
