/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kuis;

/**
 *
 * @author FRADILA
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HargaBarang1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        HargaBarang2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HargaBarang3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        HargaBarang4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Diskon = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Hasil = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 20, 110, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Harga Barang 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 80, 90, 30);
        getContentPane().add(HargaBarang1);
        HargaBarang1.setBounds(260, 80, 260, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Harga Barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 120, 90, 30);
        getContentPane().add(HargaBarang2);
        HargaBarang2.setBounds(260, 120, 260, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Harga Barang 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 160, 90, 30);

        HargaBarang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaBarang3ActionPerformed(evt);
            }
        });
        getContentPane().add(HargaBarang3);
        HargaBarang3.setBounds(260, 160, 260, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Harga Barang 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 200, 90, 30);

        HargaBarang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaBarang4ActionPerformed(evt);
            }
        });
        getContentPane().add(HargaBarang4);
        HargaBarang4.setBounds(260, 200, 260, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Diskon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 240, 50, 30);
        getContentPane().add(Diskon);
        Diskon.setBounds(260, 240, 260, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 290, 65, 23);

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 290, 63, 23);

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 290, 63, 23);
        getContentPane().add(Hasil);
        Hasil.setBounds(190, 330, 360, 150);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 510);

        setBounds(0, 0, 854, 548);
    }// </editor-fold>//GEN-END:initComponents

    private void HargaBarang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaBarang3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaBarang3ActionPerformed

    private void HargaBarang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaBarang4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaBarang4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int Harga1 = Integer.parseInt(HargaBarang1.getText());
int Harga2 = Integer.parseInt(HargaBarang2.getText());
int Harga3 = Integer.parseInt(HargaBarang3.getText());
int Harga4 = Integer.parseInt(HargaBarang4.getText());
int diskon = Integer.parseInt(Diskon.getText());
int totalHarga = Harga1 + Harga2 + Harga3 + Harga4;
int diskonBelanja = diskon / 100 * totalHarga;
int totalBayar = totalHarga - diskonBelanja;
Hasil.setText("Harga Barang 1: "+Harga1+"\nHarga Barang 2: "+Harga2+
        "\nHarga Barang 3: "+Harga3+"\nHarga Barang 4: "+Harga4+"\nDiskon :"+diskon+
        "\n Total Harga :"+totalHarga+"\nDiskon Belanja :"+diskonBelanja+"\nTotal Bayar :"+totalBayar);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Hasil.setText("");
HargaBarang1.setText("");
HargaBarang2.setText("");
HargaBarang3.setText("");
HargaBarang4.setText("");
Diskon.setText("");
buttonGroup1.clearSelection();
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Diskon;
    private javax.swing.JTextField HargaBarang1;
    private javax.swing.JTextField HargaBarang2;
    private javax.swing.JTextField HargaBarang3;
    private javax.swing.JTextField HargaBarang4;
    private javax.swing.JTextField Hasil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
